### PR TITLE
feat: scoped css

### PR DESCRIPTION
**Pull request by pantharshit00**
## What type of PR is this?

- [x] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Documentation Update

## Description

This PR adds support for scoped styles in abell components. After this PR is merged you will be able to scope the styles to a specific component automatically:
```html
<AbellComponent>
<template>
  <div>This is a test component for testing scoped css.{{ props.foo }}</div>
</template>
<style>
  div {
    color: #f30;
  }
</style>
</AbellComponent>
```

That will generate the following code:
```html
<div data-abell-efDpsM>This is a test component for testing scoped css.123</div>
<style>div[data-abell-efDpsM]{color:#f30;}</style>
```

Another conscience of this PR is that we have stylis parsing our css so you can use sass like prefixes and nest styles:
```html
<style>
  div {
    color: #f30;
    &:hover {
      color: #000;
    }
  }
</style>
```
You can also opt out and make this global style rule by using the global attribute:
```html
<AbellComponent>
<template>
  <div>This is a test component for testing global css.</div>
</template>
<style global>
  div {
    color: #f30;
  }
</style>
</AbellComponent>
```

Screenshots:
image
image

## Added unit tests?

- [ ] No, I want help in writing tests.
- [ ] No, I want someone else to write tests.
- [ ] No, The addition does not need tests.
- [x] Yes

### CODE REVIEW

**Comment by saurabhdaware** [comment]
Code looks great! I'll try testing it locally probably tomorrow. Thank youuu!

**Comment by pantharshit00** [comment]
@saurabhdaware not fully ready yet, I need a good hashing function to generate a decent hash. Also, tests are failing as they don't account for the hash.

**Comment by pantharshit00** [comment]
Also, I would love to move to jest for testing. Doing snapshot tests for this would be much wasier and mocha doesn't seem to have good snapshot test support. 

I can port the tests to jest if you agree.

**Comment by saurabhdaware** [comment]
yeah using jest shouldn't be a problem you can go ahead.

Why do we need hash exactly? what if we just add `abell-<component name>` as attribute valur?

**Comment by pantharshit00** [comment]
> Why do we need hash exactly? what if we just add abell-<component name> as attribute valur?

We can use that as people can have two different components with the same name on a different file path. I am planning to calculate a stable hash using the file path.

**Comment by pantharshit00** [comment]
@saurabhdaware Functionality is complete 🚀 . You can pull this PR and try it locally. I need to add tests now.

image
image

**Comment by saurabhdaware** [comment]
> We cannot use that as people can have two different components with the same name on a different file path. I am planning to calculate a stable hash using the file path.

Oh yes, forgot. Also, Yay!! I will test it locally by evening or tomorrow

**Review by saurabhdaware — COMMENTED** [review]
I checked it offline and it looks and works great Harshit!!

**Comment by pantharshit00** [comment]
Thanks @saurabhdaware :) 

I will add unit tests when I will get some time this week or I will add them on the weekend

**Comment by saurabhdaware** [comment]
Yes yes anytime! Also, do you mind adding comments to code on how it exactly works? I am learning the whole compilation process with AST now so it will act as a good example :D

**Comment by pantharshit00** [comment]
Ok, tests are failing because we use the component path as the hashing key which would be different per machine. I need to figure this out now...

**Comment by pantharshit00** [comment]
ok, damn you windows

**Comment by saurabhdaware** [comment]
I think its because in linux and mac paths use '/' and in windows they use '\' so is it making difference?

**Comment by pantharshit00** [comment]
Yes, I will fix it but its just annoying... :P

**Comment by saurabhdaware** [comment]
haha yesss ikrr half of commits in Abell are 'fix for windows' 😂😂🙈

**Comment by saurabhdaware** [comment]
Can we have a temporary workaround to have global as a default behavior and maybe a attribute called `scoped` to have scoped styles just to not break default API? We can replace default behavior in 1.0.0 later. Is it complicated to change?

**Comment by pantharshit00** [comment]
@saurabhdaware I can do that but I don't see any value right now for not doing that in 0.6 instead of 1.0


There are not many users right now and this will make things pretty simple for many people. We can be more careful about breaking changes after having a larger user base or after 1.0

**Comment by saurabhdaware** [comment]
Oh yeah makes sense. I can literally send PRs to those 2-3 people who are using abell 😂

**Comment by pantharshit00** [comment]
@saurabhdaware most likely they won't even need to change anything if the styles are only used per component basis and not altering global things.

**Comment by saurabhdaware** [comment]
Yup true and in starters they are used per components basis only so shouldn't be a problem. Also had mentioned in the documentation that in future we will have scoped styles. 

Is the PR ready to review now?

**Comment by pantharshit00** [comment]
@saurabhdaware sorry for late reply. Going to add tests now, I will msg you when it will be ready

**Comment by pantharshit00** [comment]
@saurabhdaware Its ready now :tada:

I have added necessary tests and I have also fixed 1-2 bugs which got uncovered via the tests.


Adds some comments as well.

**Review by saurabhdaware — APPROVED** [review]
Looks great @pantharshit00 :tada: Thank you soo muchhhh biggg helpppp!! 

I am almost done with refactoring on the other branch so I'll merge this and the other branch on next and then to the main branch

Thank you soo much!!

**Pull request merged**
