### PR TITLE
Requiring invalid files throws error

### PR DESCRIPTION
**Pull request by Pika1998**

### CODE REVIEW

**Comment by Pika1998** [comment]
Please test this

**Comment by Pika1998** [comment]
Something seems wrong. I definitely did not change 45 files XD

**Comment by Pika1998** [comment]
I am also getting these errors in console after i do 
```
cd examples/main
```
```
abell serve
```

Errors:-
image

**Comment by saurabhdaware** [comment]
oh wait did you take pull from different banch? it is not supposed to show so many changes

**Comment by Pika1998** [comment]
what i did was 
```shell
git pull upstream main
```

```shell
git push origin master
```

**Comment by saurabhdaware** [comment]
When was the last time you git pull upstream main? I think you have the old code. A week ago we retactored the whole code

**Comment by Pika1998** [comment]
yes, it has been a long time since I pulled it, what should I do now?

**Comment by saurabhdaware** [comment]
git pull upstream main
but... it will create lots of lots of conflicts :(


The easier option would be to take an upstream pull in new branch and copy paste your changes there.

**Comment by Pika1998** [comment]
ok ill try to do that

**Comment by Pika1998** [comment]
ill send a new PR

**Pull request closed without merging**
